### ISSUE TITLE
Workaround for branch protection rules

### ISSUE THREAD

**Issue by survyvaish** [tukasz/direct-merge-action#17]
We have our `dev` branch "protected" such that it requires developers to get pull requests approved before they can merge them in. This causes the direct-merge-action to fail with the following error: 

```
Error: An unexpected error occurred: protected branch 'dev' check failed:
  At least 1 approving review is required by reviewers with write access.
```

Any thoughts on how I can work around this?

**Comment by tukasz** [comment]
@survyvaish, what kind of behavior would you expect in such case? Should the `dev` branch be merged anyway, even without required review?

**Comment by survyvaish** [comment]
> @survyvaish, what kind of behavior would you expect in such case? Should the `dev` branch be merged anyway, even without required review?

Yeah. Perhaps a flag to skip the required review?

**Comment by tukasz** [comment]
Ok. Let me check if the Github API gives such possibility...

**Comment by tukasz** [comment]
I've found a thread which describes a similar scenario. This specific post has some details about creating an admin account on the repo. In this case admin user can perform actions on protected branches. Then a token is created for the admin user.

I think you could try with this approach and use the admin user's token as `GITHUB_TOKEN` input for the `direct-merge-action`.

https://github.community/t/how-to-push-to-protected-branches-in-a-github-action/16101/35

**Comment by survyvaish** [comment]
Thanks so much!! I’ll give it a shot.

**Comment by tukasz** [comment]
I forgot to add the link to the actual post <facepalm>

**Comment by dawesc** [comment]
Sadly i got this trying the above
```
An unexpected error occurred: Parameter token or opts.auth is required
```

This is the workflow definition:
```
# .github/workflows/main.yml

name: Main workflow

on:
  push:
    branches: [develop]

jobs:
  merge-develop-to-altron:
    runs-on: ubuntu-latest

    steps:
      - name: Merge Develop to altron
        uses: tukasz/direct-merge-action@v1.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          source-branch: develop
          target-branch: altron
```
